/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#include "ffshader.h"

#include <stdio.h>

// The texture factor and the sampler registers the generated shader expects the caller to have
// filled.  They are the constant register D3DRS_TEXTUREFACTOR is copied into and the stage samplers
// the device already has bound, so nothing about how a draw is set up has to change.
static const char * const TEXTURE_FACTOR_REGISTER = "c0";

// D3DTA_SELECTMASK is the argument itself; the two flags above it are modifiers the device applies
// to whatever the argument turned out to be.
static const DWORD ARGUMENT_SELECT_MASK = D3DTA_SELECTMASK;

// The low half of D3DTSS_TEXCOORDINDEX is the coordinate set; the high half is a generation mode.
static const DWORD COORDINATE_SET_MASK = 0xffff;

// The shader declares two coordinate sets, which is every one the four measured maps ask for.  A
// third is a refusal rather than a shader that samples a register it never declared.
static const unsigned DECLARED_COORDINATE_SETS = 2;

// Which texture coordinate register a stage reads.  Only the coordinate set is read; a generation
// mode is a vertex-side job and the vertex pipeline is still the fixed-function one, so a generated
// coordinate has already been generated by the time it arrives here.  Routing a generating stage to
// its own stage register instead is the other reading of the documentation and it was measured:
// on Flash Effect at frame 400 it takes the difference against the fixed-function frame from 0.25%
// to 0.81%, so the set is what the device means.
static unsigned coordinate_register(DWORD texture_coordinate_index)
{
	return static_cast<unsigned>(texture_coordinate_index & COORDINATE_SET_MASK);
}

// "current" is initialised to the diffuse colour, which is what the device gives D3DTA_CURRENT at
// stage 0, so the two need no distinguishing here.
static bool argument_expression(DWORD argument, std::string & expression)
{
	switch (argument & ARGUMENT_SELECT_MASK) {
	case D3DTA_DIFFUSE:  expression = "input.Diffuse";  break;
	case D3DTA_CURRENT:  expression = "current"; break;
	case D3DTA_TEXTURE:  expression = "texel"; break;
	case D3DTA_TFACTOR:  expression = "TextureFactor"; break;
	case D3DTA_SPECULAR: expression = "input.Specular"; break;
	default:
		return false;
	}

	// Replicate first, complement second: that is the order the reference rasteriser applies them,
	// so 1 - a.a and not (1 - a).a for an argument carrying both.
	if ((argument & D3DTA_ALPHAREPLICATE) != 0) {
		expression = "(" + expression + ").aaaa";
	}
	if ((argument & D3DTA_COMPLEMENT) != 0) {
		expression = "(1.0 - " + expression + ")";
	}
	return true;
}

static bool operation_expression(DWORD operation, const std::string & argument0,
	const std::string & argument1, const std::string & argument2, std::string & expression)
{
	switch (operation) {
	case D3DTOP_SELECTARG1:
		expression = argument1;
		return true;
	case D3DTOP_SELECTARG2:
		expression = argument2;
		return true;
	case D3DTOP_MODULATE:
		expression = "(" + argument1 + " * " + argument2 + ")";
		return true;
	case D3DTOP_MODULATE2X:
		expression = "(" + argument1 + " * " + argument2 + " * 2.0)";
		return true;
	case D3DTOP_MODULATE4X:
		expression = "(" + argument1 + " * " + argument2 + " * 4.0)";
		return true;
	case D3DTOP_ADD:
		expression = "(" + argument1 + " + " + argument2 + ")";
		return true;
	case D3DTOP_ADDSIGNED:
		expression = "(" + argument1 + " + " + argument2 + " - 0.5)";
		return true;
	case D3DTOP_SUBTRACT:
		expression = "(" + argument1 + " - " + argument2 + ")";
		return true;
	case D3DTOP_MULTIPLYADD:
		expression = "(" + argument0 + " + " + argument1 + " * " + argument2 + ")";
		return true;
	case D3DTOP_LERP:
		expression = "lerp(" + argument2 + ", " + argument1 + ", " + argument0 + ")";
		return true;
	case D3DTOP_DOTPRODUCT3:
		// The device works on signed values here and saturates the result into all four channels.
		expression = "saturate(dot((" + argument1 + ").rgb * 2.0 - 1.0, ("
			+ argument2 + ").rgb * 2.0 - 1.0)).xxxx";
		return true;
	default:
		return false;
	}
}

// D3D11 has no alpha test, so the comparison becomes a clip.  clip() throws the pixel away when its
// argument is negative, which turns each comparison into one subtraction.  The two that ask about
// equality need a tolerance, and there is no exactly right one: a D3D9 alpha test compared eight
// bit integers and this compares floats, so half a step of eight bit precision is the tolerance
// used and it is a choice rather than a translation.
static const char * const ALPHA_EQUALITY_TOLERANCE = "0.00196";

static bool alpha_test_expression(DWORD function, std::string & expression)
{
	switch (function) {
	case D3DCMP_NEVER:
		expression = "clip(-1.0);\n";
		return true;
	case D3DCMP_LESS:
	case D3DCMP_LESSEQUAL:
		expression = "clip(AlphaReference.x - current.a);\n";
		return true;
	case D3DCMP_GREATER:
	case D3DCMP_GREATEREQUAL:
		expression = "clip(current.a - AlphaReference.x);\n";
		return true;
	case D3DCMP_EQUAL:
		expression = std::string("clip(") + ALPHA_EQUALITY_TOLERANCE
			+ " - abs(current.a - AlphaReference.x));\n";
		return true;
	case D3DCMP_NOTEQUAL:
		expression = std::string("clip(abs(current.a - AlphaReference.x) - ")
			+ ALPHA_EQUALITY_TOLERANCE + ");\n";
		return true;
	case D3DCMP_ALWAYS:
		// Nothing to write: every pixel survives, which is what no alpha test at all means.
		expression.clear();
		return true;
	default:
		return false;
	}
}

bool CombinerShader_Generate(const CombinerDescription & description, CombinerShaderTarget target,
	std::string & hlsl)
{
	if (description.StageCount == 0 || description.StageCount > MAXIMUM_COMBINER_STAGES) {
		return false;
	}

	std::string body;
	for (unsigned stage = 0; stage < description.StageCount; ++stage) {
		const CombinerStage & source = description.Stages[stage];

		char line[256];
		if (source.TextureBound) {
			const unsigned register_index = coordinate_register(source.TextureCoordinateIndex);
			if (register_index >= DECLARED_COORDINATE_SETS) {
				return false;
			}
			if (target == COMBINER_SHADER_TARGET_D3D11) {
				snprintf(line, sizeof(line),
					"    texel = Texture%u.Sample(Sampler%u, input.TexCoord%u);\n",
					stage, stage, register_index);
			}
			else {
				snprintf(line, sizeof(line), "    texel = tex2D(Sampler%u, input.TexCoord%u);\n",
					stage, register_index);
			}
		}
		else {
			// What a stage with no texture bound gives D3DTA_TEXTURE is not something this can
			// assert: the documentation does not say and reports of what hardware does disagree.
			// Opaque white is the choice that makes MODULATE a no-op, which is what the call sites
			// that leave a stage untextured appear to want, and one measured combination reads
			// D3DTA_TEXTURE with nothing bound - SELECTARG1 on an untextured stage - so the two
			// answers are distinguishable on screen.  tree-check.ps1 settles it, not this comment.
			snprintf(line, sizeof(line), "    texel = float4(1.0, 1.0, 1.0, 1.0);\n");
		}
		body += line;

		std::string colour_argument0, colour_argument1, colour_argument2;
		std::string alpha_argument0, alpha_argument1, alpha_argument2;
		if (!argument_expression(source.ColourArgument0, colour_argument0)
			|| !argument_expression(source.ColourArgument1, colour_argument1)
			|| !argument_expression(source.ColourArgument2, colour_argument2)
			|| !argument_expression(source.AlphaArgument0, alpha_argument0)
			|| !argument_expression(source.AlphaArgument1, alpha_argument1)
			|| !argument_expression(source.AlphaArgument2, alpha_argument2)) {
			return false;
		}

		std::string colour_expression;
		std::string alpha_expression;
		if (!operation_expression(source.ColourOperation, colour_argument0, colour_argument1,
				colour_argument2, colour_expression)
			|| !operation_expression(source.AlphaOperation, alpha_argument0, alpha_argument1,
				alpha_argument2, alpha_expression)) {
			return false;
		}

		// Every stage of the fixed-function combiner writes a clamped result, and the next stage
		// reads that clamped value out of D3DTA_CURRENT.  A shader that carries the raw arithmetic
		// forward instead comes out brighter wherever MODULATE2X, MODULATE4X, ADD or MULTIPLYADD
		// left a term above one, and darker where SUBTRACT or ADDSIGNED went below zero.
		body += "    current.rgb = saturate(" + colour_expression + ").rgb;\n";
		body += "    current.a   = saturate(" + alpha_expression + ").a;\n";
	}

	// The full input signature is declared whether the program reads it or not.  Trimming it to
	// what the body names is the obvious economy and it was measured: on Flash Effect at frame 400
	// it takes the difference against the fixed-function frame from 0.25% to 1.20%.  Why a program
	// that reads no diffuse colour draws differently for having declared one is not understood.
	hlsl = "// Generated from a fixed-function texture stage description.  See ffshader.h.\n";
	if (target == COMBINER_SHADER_TARGET_D3D11) {
		// A texture and the sampler that reads it are separate objects here, and the texture
		// factor is a constant buffer field rather than a register.
		hlsl +=
			"Texture2D Texture0 : register(t0);\n"
			"Texture2D Texture1 : register(t1);\n"
			"SamplerState Sampler0 : register(s0);\n"
			"SamplerState Sampler1 : register(s1);\n"
			"cbuffer CombinerConstants : register(b0)\n"
			"{\n"
			"    float4 TextureFactor;\n"
			"    float4 FogColour;\n"
			"    float4 AlphaReference;\n"
			"};\n";
	}
	else {
		hlsl +=
			"sampler2D Sampler0 : register(s0);\n"
			"sampler2D Sampler1 : register(s1);\n"
			"float4 TextureFactor : register(";
		hlsl += TEXTURE_FACTOR_REGISTER;
		hlsl += ");\n";
	}
	hlsl +=
		"\n"
		"struct Input\n"
		"{\n";

	// Shader model 4 links the two stages by register slot, not by name, and it assigns those
	// slots in declaration order.  A vertex shader whose output opens with SV_Position and closes
	// with the fog factor puts the diffuse colour in the second slot; a pixel shader that declares
	// neither puts it in the first, and D3D11 refuses the draw with a linkage error naming COLOR
	// and TEXCOORD.  So the D3D11 input structure is ffvertex's output structure, member for
	// member, whether this program reads all of it or not.  ps_2_0 has no such rule.
	if (target == COMBINER_SHADER_TARGET_D3D11) {
		hlsl += "    float4 Position  : SV_Position;\n";
	}
	hlsl +=
		"    float4 Diffuse   : COLOR0;\n"
		"    float4 Specular  : COLOR1;\n"
		"    float2 TexCoord0 : TEXCOORD0;\n"
		"    float2 TexCoord1 : TEXCOORD1;\n";
	if (target == COMBINER_SHADER_TARGET_D3D11) {
		hlsl += "    float Fog        : FOG;\n";
	}
	hlsl +=
		"};\n"
		"\n";
	hlsl += (target == COMBINER_SHADER_TARGET_D3D11)
		? "float4 main(Input input) : SV_Target\n"
		: "float4 main(Input input) : COLOR\n";
	hlsl +=
		"{\n"
		"    float4 texel;\n"
		"    float4 current = input.Diffuse;\n";
	hlsl += body;

	if (target == COMBINER_SHADER_TARGET_D3D11) {
		// The fog is applied after the combiners and before the alpha test, which is the order the
		// D3D9 pipeline applies them in.  The factor is the weight of the unfogged colour, so one
		// is no fog, and it never touches the alpha - a fogged pixel is the same shape as an
		// unfogged one.
		if (description.PixelPipeline.FogEnabled) {
			hlsl += "    current.rgb = lerp(FogColour.rgb, current.rgb, saturate(input.Fog));\n";
		}

		if (description.PixelPipeline.AlphaTestEnabled) {
			std::string clip;
			if (!alpha_test_expression(description.PixelPipeline.AlphaFunction, clip)) {
				return false;
			}
			if (!clip.empty()) {
				hlsl += "    " + clip;
			}
		}
	}

	hlsl +=
		"    return current;\n"
		"}\n";
	return true;
}

std::string CombinerShader_Key(const CombinerDescription & description)
{
	std::string key;
	char field[32];
	snprintf(field, sizeof(field), "%u", description.StageCount);
	key += field;

	for (unsigned stage = 0; stage < description.StageCount; ++stage) {
		const CombinerStage & source = description.Stages[stage];
		snprintf(field, sizeof(field), ":%lu,%lu,%lu,%lu",
			source.ColourOperation, source.ColourArgument0,
			source.ColourArgument1, source.ColourArgument2);
		key += field;
		snprintf(field, sizeof(field), ",%lu,%lu,%lu,%lu",
			source.AlphaOperation, source.AlphaArgument0,
			source.AlphaArgument1, source.AlphaArgument2);
		key += field;
		snprintf(field, sizeof(field), ",%u,%u",
			coordinate_register(source.TextureCoordinateIndex), source.TextureBound ? 1u : 0u);
		key += field;
	}

	// The alpha test and the fog change the program on the D3D11 profile.  They are in the key on
	// both, which costs a D3D9 cache entry that generates the same text as another and buys one
	// cache that is right for either profile.
	snprintf(field, sizeof(field), ":A%u,%lu,F%u",
		description.PixelPipeline.AlphaTestEnabled ? 1u : 0u,
		description.PixelPipeline.AlphaTestEnabled ? description.PixelPipeline.AlphaFunction : 0ul,
		description.PixelPipeline.FogEnabled ? 1u : 0u);
	key += field;
	return key;
}
