/*
**	Command & Conquer Generals Zero Hour(tm)
**	Copyright 2025 Electronic Arts Inc.
**
**	This program is free software: you can redistribute it and/or modify
**	it under the terms of the GNU General Public License as published by
**	the Free Software Foundation, either version 3 of the License, or
**	(at your option) any later version.
**
**	This program is distributed in the hope that it will be useful,
**	but WITHOUT ANY WARRANTY; without even the implied warranty of
**	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
**	GNU General Public License for more details.
**
**	You should have received a copy of the GNU General Public License
**	along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

// RandomMapGenerator.h
// Builds a complete .map image in memory from a seed, so a match can be played
// on a map that was never written to disk.

#pragma once

#ifndef __RANDOMMAPGENERATOR_H_
#define __RANDOMMAPGENERATOR_H_

#include "Common/STLTypedefs.h"
#include "Common/MapReaderWriterInfo.h"

/** Version of the generated bytes. Bump it whenever the generator's output
	changes for unchanged settings: it travels with the seed in multiplayer, so
	a build that generates a different map is caught before the match starts
	rather than desyncing partway through it. The fingerprint test in
	test_gameengine.cpp fails until the version and the recorded CRCs agree, so
	the bump cannot be forgotten. */
#define RANDOM_MAP_GENERATOR_VERSION 2

/** Everything the generator is allowed to read. Two machines handed the same
	settings must produce byte-identical maps, so nothing else - no clock, no
	options file, no global state - may leak into generate(). */
struct RandomMapSettings
{
	Int m_seed;						///< drives the whole layout
	Int m_playableCells;			///< cells per side of the playable area
	Int m_numPlayers;				///< start positions to place

	RandomMapSettings() : m_seed(0), m_playableCells(160), m_numPlayers(2) { }
};

class RandomMapGenerator
{
public:
	enum { MIN_PLAYERS = 2, MAX_PLAYERS = 8 };
	enum { MIN_CELLS = 64, MAX_CELLS = 512 };
	enum { PREVIEW_PIXELS = 128 };		///< what getMapPreviewImage expects of the tga

	/// Build an uncompressed CkMp map image. Deterministic in the settings alone.
	static void generate( const RandomMapSettings& settings, std::vector<char>& mapBytes );

	/// A 128x128 24-bit tga of the same layout, for the map list entry.
	static void generatePreview( const RandomMapSettings& settings, std::vector<char>& tgaBytes );

	/** CRC of the generated bytes with the generator version folded in. Two
		builds that agree on this agree on the map; the test suite pins it. */
	static UnsignedInt fingerprint( const RandomMapSettings& settings );

	/// Settings clamped the way generate() clamps them, so callers can report the truth.
	static void clampSettings( RandomMapSettings& settings );
};

/** Generate the map and its preview and write both into the user map directory,
	under a name that carries the generator version and the settings, so two
	different maps never land on one file. Returns false when the file could not
	be written; on success mapPathOut is what -map wants. */
extern Bool writeRandomMap( const RandomMapSettings& settings, AsciiString& mapPathOut );

/** A ChunkInputStream over a block of memory, so a generated map can be handed
	to the same readers that parse maps off disk. */
class MemoryChunkInputStream : public ChunkInputStream
{
public:
	MemoryChunkInputStream( const char *data, Int size );

	virtual Int read( void *pData, Int numBytes );
	virtual UnsignedInt tell( void );
	virtual Bool absoluteSeek( UnsignedInt pos );
	virtual Bool eof( void );

private:
	const char *m_data;
	Int m_size;
	Int m_pos;
};

#endif  // __RANDOMMAPGENERATOR_H_
